In [2]:
import torch
import numpy as np
import pandas as pd
from LeNet5 import LeNet5

In [3]:
model = LeNet5()

In [3]:
model.named_parameters

<bound method Module.named_parameters of LeNet5(
  (c1): C1(
    (c1): Sequential(
      (c1): Conv2d(1, 20, kernel_size=(5, 5), stride=(1, 1))
      (relu1): ReLU()
      (mp1): MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
    )
  )
  (c2): C2(
    (c2): Sequential(
      (c2): Conv2d(20, 50, kernel_size=(5, 5), stride=(1, 1))
      (relu2): ReLU()
      (mp2): MaxPool2d(kernel_size=(2, 2), stride=2, padding=0, dilation=1, ceil_mode=False)
    )
  )
  (fc1): FC1(
    (fc1): Sequential(
      (fc1): Linear(in_features=800, out_features=500, bias=True)
      (relu3): ReLU()
    )
  )
  (fc2): FC2(
    (fc2): Sequential(
      (fc2): Linear(in_features=500, out_features=10, bias=True)
      (sig4): LogSoftmax(dim=-1)
    )
  )
)>

In [4]:
# load the best model and param
model.load_state_dict(torch.load('best.pt'))
print('Successfully loaded from ckpt!\n')

Successfully loaded from ckpt!



In [5]:
# optimal param of model
print("Model's named_parameters:")
for name, parameters in model.named_parameters():
    print(name, parameters)

Model's named_parameters:
c1.c1.c1.weight Parameter containing:
tensor([[[[-1.5711e-01, -8.8273e-02, -2.1924e-01, -2.0340e-01, -2.7370e-01],
          [ 1.3321e-01, -1.6852e-01, -1.9650e-02,  3.6659e-02, -5.5700e-02],
          [ 2.1765e-01,  1.5023e-01,  2.1408e-01,  2.1385e-01, -2.6975e-02],
          [ 1.2311e-01, -1.2739e-02,  1.3655e-01, -3.4293e-02,  1.2268e-01],
          [ 2.2200e-02, -6.2511e-02, -7.5782e-02,  7.8226e-02,  1.9521e-01]]],


        [[[ 6.8129e-02, -4.4022e-02, -2.4512e-02,  8.0977e-02, -2.4196e-01],
          [ 8.6066e-02, -3.6721e-02,  1.7547e-01, -2.4433e-02, -8.8315e-02],
          [ 8.2429e-02,  1.4625e-01,  6.4728e-02,  3.0192e-01, -2.6246e-01],
          [-6.6666e-02, -2.6664e-01,  5.6942e-02,  1.8581e-01, -8.5667e-02],
          [ 2.2267e-02, -1.3033e-01, -2.0672e-01,  2.1883e-01,  1.5964e-01]]],


        [[[ 1.5678e-01,  2.3902e-01,  1.8037e-01,  2.2261e-01,  2.6595e-01],
          [ 3.5717e-03, -1.1280e-01, -3.6371e-02,  3.6436e-02,  2.6336e-02],
    

In [6]:
# Print optimizer's state_dict
import torch.optim as optim
learning_rate = 0.001
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

print("Optimizer's state_dict:")
for var_name in optimizer.state_dict():
    print(var_name, "\t", optimizer.state_dict()[var_name])

Optimizer's state_dict:
state 	 {}
param_groups 	 [{'lr': 0.001, 'betas': (0.9, 0.999), 'eps': 1e-08, 'weight_decay': 0, 'amsgrad': False, 'params': [0, 1, 2, 3, 4, 5, 6, 7]}]


In [7]:
# optimal param of model
# save param in dict

param = {}
for name, parameters in model.named_parameters():
    print(name,':', parameters.size())
    param[name] = parameters.detach().numpy()

c1.c1.c1.weight : torch.Size([20, 1, 5, 5])
c1.c1.c1.bias : torch.Size([20])
c2.c2.c2.weight : torch.Size([50, 20, 5, 5])
c2.c2.c2.bias : torch.Size([50])
fc1.fc1.fc1.weight : torch.Size([500, 800])
fc1.fc1.fc1.bias : torch.Size([500])
fc2.fc2.fc2.weight : torch.Size([10, 500])
fc2.fc2.fc2.bias : torch.Size([10])


In [8]:
param['c1.c1.c1.weight']

array([[[[-1.57111257e-01, -8.82725641e-02, -2.19239578e-01,
          -2.03399852e-01, -2.73699760e-01],
         [ 1.33207038e-01, -1.68519944e-01, -1.96500439e-02,
           3.66585925e-02, -5.56998588e-02],
         [ 2.17647433e-01,  1.50232345e-01,  2.14081734e-01,
           2.13852197e-01, -2.69754063e-02],
         [ 1.23113669e-01, -1.27388136e-02,  1.36553168e-01,
          -3.42926569e-02,  1.22680634e-01],
         [ 2.22004373e-02, -6.25108778e-02, -7.57816732e-02,
           7.82257095e-02,  1.95214778e-01]]],


       [[[ 6.81290105e-02, -4.40222695e-02, -2.45124921e-02,
           8.09765235e-02, -2.41957128e-01],
         [ 8.60660970e-02, -3.67211886e-02,  1.75469875e-01,
          -2.44332310e-02, -8.83150026e-02],
         [ 8.24290216e-02,  1.46249905e-01,  6.47276342e-02,
           3.01916391e-01, -2.62460768e-01],
         [-6.66664988e-02, -2.66639262e-01,  5.69415577e-02,
           1.85809344e-01, -8.56674686e-02],
         [ 2.22668890e-02, -1.30329981e-01

In [9]:
param['c1.c1.c1.bias']

array([ 0.00050227,  0.02436067, -0.07738867,  0.15644082, -0.06640333,
       -0.00080405,  0.01804296,  0.00180055,  0.04983768,  0.03052647,
       -0.002885  , -0.00774574,  0.05583518,  0.00147747, -0.03978303,
        0.01121474, -0.00172322,  0.07938362, -0.05205339,  0.03379398],
      dtype=float32)

In [14]:
# 定义函数:将某一层权重/偏置参数保存到表格中 (dim=2)
def param_to_excel(excel_name, key_name, param):
    
    param_len = len(param[key_name].shape)
    with pd.ExcelWriter(excel_name) as writer:
        if param_len == 4:
            [output_num, input_num, filter_size,_] = list(param[key_name].shape)
            for i in range(output_num):
                for j in range(input_num):
                    data = pd.DataFrame(param[key_name][i,j,:,:])
                    data.to_excel(writer, 'conv_weight', index=False, header=False, 
                                  startrow=i*(filter_size), startcol=j*filter_size)
            writer.save()
        
        elif param_len == 2:
            data = pd.DataFrame(param[key_name])
            data.to_excel(writer, 'fc_weight', index=False, header=False)
            writer.save()
        
        else:
            data = pd.DataFrame(param[key_name])
            data.to_excel(writer, 'bias', index=False, header=False)
            writer.save()

In [12]:
# 调用函数: weight
param_to_excel('c1_weight.xlsx', 'c1.c1.c1.weight', param)
param_to_excel('c2_weight.xlsx', 'c2.c2.c2.weight', param)
param_to_excel('fc1_weight.xlsx', 'fc1.fc1.fc1.weight', param)
param_to_excel('fc2_weight.xlsx', 'fc2.fc2.fc2.weight', param)

In [15]:
# 调用函数: bias
param_to_excel('c1_bias.xlsx', 'c1.c1.c1.bias', param)
param_to_excel('c2_bias.xlsx', 'c2.c2.c2.bias', param)
param_to_excel('fc1_bias.xlsx', 'fc1.fc1.fc1.bias', param)
param_to_excel('fc2_bias.xlsx', 'fc2.fc2.fc2.bias', param)

In [16]:
# 定义函数:将某一层权重/偏置参数保存到文本中 (dim=1)
def param_to_text(text_name, key_name, param):
    
    param_len = len(param[key_name].shape)
    with open(text_name, 'w') as f:
        if param_len == 4:
            [output_num, input_num, filter_h, filter_w] = list(param[key_name].shape)
            for i in range(output_num):
                for j in range(input_num):
                    for k in range(filter_h):
                        for v in range(filter_w):
                            f.write(str(param[key_name][i,j,k,v]) + '\n')
            f.close()
        
        elif param_len == 2:
            [output_num, input_num] = list(param[key_name].shape)
            for i in range(output_num):
                for j in range(input_num):
                    f.write(str(param[key_name][i,j]) + '\n')
            f.close()
            
        else:
            [bias_size] = list(param[key_name].shape)
            for i in range(bias_size):
                f.write(str(param[key_name][i]) + '\n')
            f.close

In [17]:
# 调用函数: weight
param_to_text('c1_weight.txt', 'c1.c1.c1.weight', param)
param_to_text('c2_weight.txt', 'c2.c2.c2.weight', param)
param_to_text('fc1_weight.txt', 'fc1.fc1.fc1.weight', param)
param_to_text('fc2_weight.txt', 'fc2.fc2.fc2.weight', param)

In [18]:
# 调用函数: bias
param_to_text('c1_bias.txt', 'c1.c1.c1.bias', param)
param_to_text('c2_bias.txt', 'c2.c2.c2.bias', param)
param_to_text('fc1_bias.txt', 'fc1.fc1.fc1.bias', param)
param_to_text('fc2_bias.txt', 'fc2.fc2.fc2.bias', param)